version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5438:5432'
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

  app:
    image: next-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    env_file: ./.env
    networks:
      - postgres-network
    volumes:
      - ./src:/app/src
      - ./app-logs:/var/lib/next-docker/data

# This conteiner is need for check data in BD in web interface

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres-network

volumes:
    pgdata:
      external: true
    app-logs:
      external: true

networks:
  postgres-network:
    driver: bridge
    external: false
    name: postgres-network
