version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5438:5432'
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

  app:
    image: next-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    env_file: ./.env
    networks:
      - postgres-network
    volumes:
      - ./src:/app/src

volumes:
    pgdata:
      external: true

networks:
  postgres-network:
    driver: bridge
    external: false
    name: postgres-network
