version: '3.5'

services:
  db:
    image: postgres
    restart: always
    networks:
      - postgres
    env_file:
      - ./.env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    hostname: myhost
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    depends_on:
      - db
    networks:
      - postgres
    env_file: ./.env
    environment:
      - PORT=${PORT}
    ports:
      - '3000:4000'
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
    pgdata:
      external: true

networks:
  postgres:
    driver: bridge
